

const CONSTANT = {
    DATABASE_CONNECTION: 'DATABASE_CONNECTION',

    USER_MODEL_TOKEN: 'USER_MODEL_TOKEN',
    POST_MODEL_TOKEN: 'POST_MODEL_TOKEN',
    ONLINE_MODEL_TOKEN: 'ONLINE_MODEL_TOKEN',
    MESSAGE_MODEL_TOKEN: 'MESSAGE_MODEL_TOKEN',
    MEDIA_MODEL_TOKEN: 'MEDIA_MODEL_TOKEN',

    CLOUDINARY: 'CLOUDINARY',
}

export default CONSTANT;